# Radiant Savanna - Solar Lion (YELLOW REALM) - Rewards:
hit1Reward=null
hit2Reward=null
hit3Reward=TimeWarp
hit4Reward=null
hit5Reward=RedBonus
hit6Reward=ArcaneBoost
hit7Reward=null
hit8Reward=ElementalCrest
hit9Reward=null
hit10Reward=MagentaBonus
hit11Reward=null
hit1Multiplier=null
hit2Multiplier=null
hit3Multiplier=null
hit4Multiplier=2
hit5Multiplier=null
hit6Multiplier=null
hit7Multiplier=2
hit8Multiplier=null
hit9Multiplier=2    
hit10Multiplier=null
hit11Multiplier=3